package dbos

import (
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net"
	"net/url"
	"strings"

	"github.com/jackc/pgerrcode"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// dialect.go contains PostgreSQL error classification and database-URL validation.
// DBOS targets PostgreSQL only; queries are generated by sqlc and table references
// are resolved through the connection's search_path (see newKernel).

// validateDatabaseURL checks that a DBOS database URL names a PostgreSQL backend.
// It accepts both URL form (postgres://, postgresql://) and the libpq key=value
// DSN form (e.g. "user=... host=...").
func validateDatabaseURL(rawURL string) error {
	if rawURL == "" {
		return fmt.Errorf("database URL is empty")
	}
	// libpq key=value DSNs can contain characters that url.Parse rejects, so detect
	// that form first before falling through to url.Parse.
	if looksLikePostgresKVDSN(rawURL) {
		return nil
	}
	u, err := url.Parse(rawURL)
	if err != nil {
		return fmt.Errorf("invalid database URL: %v", err)
	}
	switch strings.ToLower(u.Scheme) {
	case "postgres", "postgresql":
		return nil
	case "":
		return fmt.Errorf("database URL has no scheme: %q", rawURL)
	default:
		return fmt.Errorf("unsupported database scheme %q (want postgres:)", u.Scheme)
	}
}

// looksLikePostgresKVDSN matches the libpq key=value connection-string form by
// checking for a leading canonical keyword.
func looksLikePostgresKVDSN(s string) bool {
	lower := strings.ToLower(strings.TrimSpace(s))
	for _, prefix := range []string{
		"user=", "host=", "hostaddr=", "port=", "dbname=", "database=",
		"password=", "sslmode=", "application_name=", "options=",
	} {
		if strings.HasPrefix(lower, prefix) {
			return true
		}
	}
	return false
}

// pgErrCode extracts the SQLSTATE code from a pgconn.PgError, or "" if err is
// not a pg error.
func pgErrCode(err error) string {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		return pgErr.Code
	}
	return ""
}

func isUniqueViolation(err error) bool {
	return pgErrCode(err) == pgerrcode.UniqueViolation
}

func isForeignKeyViolation(err error) bool {
	return pgErrCode(err) == pgerrcode.ForeignKeyViolation
}

// isRetryable matches transient PostgreSQL driver errors that can be safely
// retried: closed transaction handles, connection-level SQLSTATEs, pgx connect
// failures, EOF/closed-conn strings, and net.Error. Serialization /
// lock-not-available SQLSTATEs are intentionally excluded because those require
// retrying the entire transaction. The signature matches
// retryConfig.retryConditionChain so a function value can be inserted directly.
func isRetryable(err error, logger *slog.Logger) bool {
	if err == nil {
		return false
	}
	// pgx surfaces ErrTxClosed for ops on a tx that has already finalized;
	// the caller must retry with a fresh tx.
	if errors.Is(err, pgx.ErrTxClosed) {
		if logger != nil {
			logger.Warn("Transaction is closed, retrying requires a new transaction object", "error", err)
		}
		return true
	}
	var pgerr *pgconn.PgError
	if errors.As(err, &pgerr) {
		switch pgerr.Code {
		case pgerrcode.ConnectionException,
			pgerrcode.ConnectionDoesNotExist,
			pgerrcode.ConnectionFailure,
			pgerrcode.SQLClientUnableToEstablishSQLConnection,
			pgerrcode.SQLServerRejectedEstablishmentOfSQLConnection,
			pgerrcode.AdminShutdown,
			pgerrcode.CrashShutdown,
			pgerrcode.CannotConnectNow:
			return true
		}
	}
	var cerr *pgconn.ConnectError
	if errors.As(err, &cerr) {
		return true
	}
	if errors.Is(err, io.EOF) || strings.Contains(err.Error(), "conn closed") {
		return true
	}
	var nerr net.Error
	return errors.As(err, &nerr)
}
