// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aggregates.sql

package db

import (
	"context"
)

const getStepAggregates = `-- name: GetStepAggregates :many
SELECT
    CASE WHEN $1::boolean THEN function_name ELSE NULL END AS g_function_name,
    CASE WHEN $2::boolean
        THEN (CASE WHEN error IS NULL THEN 'SUCCESS' ELSE 'ERROR' END)
        ELSE NULL END AS g_status,
    CASE WHEN $3::boolean
        THEN CAST(FLOOR(completed_at_epoch_ms::numeric / $4::bigint) AS BIGINT) * $4::bigint
        ELSE NULL END AS g_time_bucket,
    COUNT(*) AS cnt,
    MAX(completed_at_epoch_ms - started_at_epoch_ms) AS max_duration_ms
FROM operation_outputs
WHERE (NOT $5::boolean OR (CASE WHEN error IS NULL THEN 'SUCCESS' ELSE 'ERROR' END) = ANY($6::text[]))
  AND (NOT $7::boolean OR function_name = ANY($8::text[]))
  AND (NOT $9::boolean OR workflow_uuid LIKE ANY($10::text[]))
  AND (NOT $11::boolean OR completed_at_epoch_ms >= $12::bigint)
  AND (NOT $13::boolean OR completed_at_epoch_ms <= $14::bigint)
GROUP BY 1, 2, 3
LIMIT $15::bigint
`

type GetStepAggregatesParams struct {
	GroupFunctionName     bool
	GroupStatus           bool
	GroupTimeBucket       bool
	BucketSize            int64
	FilterStatus          bool
	Statuses              []string
	FilterFunctionName    bool
	FunctionNames         []string
	FilterIDPrefix        bool
	IDPrefixes            []string
	FilterCompletedAfter  bool
	CompletedAfter        int64
	FilterCompletedBefore bool
	CompletedBefore       int64
	Lim                   int64
}

type GetStepAggregatesRow struct {
	GFunctionName interface{}
	GStatus       interface{}
	GTimeBucket   interface{}
	Cnt           int64
	MaxDurationMs interface{}
}

// Step status is derived from operation_outputs.error (NULL => SUCCESS).
// Both aggregates are always computed; the caller surfaces only the ones requested.
func (q *Queries) GetStepAggregates(ctx context.Context, arg GetStepAggregatesParams) ([]GetStepAggregatesRow, error) {
	rows, err := q.db.Query(ctx, getStepAggregates,
		arg.GroupFunctionName,
		arg.GroupStatus,
		arg.GroupTimeBucket,
		arg.BucketSize,
		arg.FilterStatus,
		arg.Statuses,
		arg.FilterFunctionName,
		arg.FunctionNames,
		arg.FilterIDPrefix,
		arg.IDPrefixes,
		arg.FilterCompletedAfter,
		arg.CompletedAfter,
		arg.FilterCompletedBefore,
		arg.CompletedBefore,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStepAggregatesRow{}
	for rows.Next() {
		var i GetStepAggregatesRow
		if err := rows.Scan(
			&i.GFunctionName,
			&i.GStatus,
			&i.GTimeBucket,
			&i.Cnt,
			&i.MaxDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflowAggregates = `-- name: GetWorkflowAggregates :many
SELECT
    CASE WHEN $1::boolean THEN status ELSE NULL END AS g_status,
    CASE WHEN $2::boolean THEN name ELSE NULL END AS g_name,
    CASE WHEN $3::boolean THEN queue_name ELSE NULL END AS g_queue_name,
    CASE WHEN $4::boolean THEN executor_id ELSE NULL END AS g_executor_id,
    CASE WHEN $5::boolean THEN application_version ELSE NULL END AS g_app_version,
    CASE WHEN $6::boolean
        THEN CAST(FLOOR(created_at::numeric / $7::bigint) AS BIGINT) * $7::bigint
        ELSE NULL END AS g_time_bucket,
    COUNT(*) AS cnt
FROM workflow_status
WHERE (NOT $8::boolean OR status = ANY($9::text[]))
  AND (NOT $10::boolean OR created_at >= $11::bigint)
  AND (NOT $12::boolean OR created_at <= $13::bigint)
  AND (NOT $14::boolean OR name = ANY($15::text[]))
  AND (NOT $16::boolean OR application_version = ANY($17::text[]))
  AND (NOT $18::boolean OR executor_id = ANY($19::text[]))
  AND (NOT $20::boolean OR queue_name = ANY($21::text[]))
  AND (NOT $22::boolean OR workflow_uuid LIKE ANY($23::text[]))
GROUP BY 1, 2, 3, 4, 5, 6
LIMIT $24::bigint
`

type GetWorkflowAggregatesParams struct {
	GroupStatus      bool
	GroupName        bool
	GroupQueue       bool
	GroupExecutor    bool
	GroupAppVersion  bool
	GroupTimeBucket  bool
	BucketSize       int64
	FilterStatus     bool
	Statuses         []string
	FilterStart      bool
	StartMs          int64
	FilterEnd        bool
	EndMs            int64
	FilterName       bool
	Names            []string
	FilterAppVersion bool
	AppVersions      []string
	FilterExecutor   bool
	ExecutorIds      []string
	FilterQueue      bool
	QueueNames       []string
	FilterIDPrefix   bool
	IDPrefixes       []string
	Lim              int64
}

type GetWorkflowAggregatesRow struct {
	GStatus     interface{}
	GName       interface{}
	GQueueName  interface{}
	GExecutorID interface{}
	GAppVersion interface{}
	GTimeBucket interface{}
	Cnt         int64
}

// Each group dimension is gated by a flag: when off, its column is NULL for all
// rows so GROUP BY collapses that dimension. Group columns are scanned as
// interface{} (string/int64/nil) and normalized to *string by the caller.
func (q *Queries) GetWorkflowAggregates(ctx context.Context, arg GetWorkflowAggregatesParams) ([]GetWorkflowAggregatesRow, error) {
	rows, err := q.db.Query(ctx, getWorkflowAggregates,
		arg.GroupStatus,
		arg.GroupName,
		arg.GroupQueue,
		arg.GroupExecutor,
		arg.GroupAppVersion,
		arg.GroupTimeBucket,
		arg.BucketSize,
		arg.FilterStatus,
		arg.Statuses,
		arg.FilterStart,
		arg.StartMs,
		arg.FilterEnd,
		arg.EndMs,
		arg.FilterName,
		arg.Names,
		arg.FilterAppVersion,
		arg.AppVersions,
		arg.FilterExecutor,
		arg.ExecutorIds,
		arg.FilterQueue,
		arg.QueueNames,
		arg.FilterIDPrefix,
		arg.IDPrefixes,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkflowAggregatesRow{}
	for rows.Next() {
		var i GetWorkflowAggregatesRow
		if err := rows.Scan(
			&i.GStatus,
			&i.GName,
			&i.GQueueName,
			&i.GExecutorID,
			&i.GAppVersion,
			&i.GTimeBucket,
			&i.Cnt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
