// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_versions.sql

package db

import (
	"context"
)

const createApplicationVersion = `-- name: CreateApplicationVersion :exec
INSERT INTO application_versions (version_id, version_name, version_timestamp, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (version_name) DO NOTHING
`

type CreateApplicationVersionParams struct {
	VersionID        string
	VersionName      string
	VersionTimestamp int64
	CreatedAt        int64
}

func (q *Queries) CreateApplicationVersion(ctx context.Context, arg CreateApplicationVersionParams) error {
	_, err := q.db.Exec(ctx, createApplicationVersion,
		arg.VersionID,
		arg.VersionName,
		arg.VersionTimestamp,
		arg.CreatedAt,
	)
	return err
}

const getLatestApplicationVersion = `-- name: GetLatestApplicationVersion :one
SELECT version_id, version_name, version_timestamp, created_at
FROM application_versions
ORDER BY version_timestamp DESC
LIMIT 1
`

func (q *Queries) GetLatestApplicationVersion(ctx context.Context) (ApplicationVersion, error) {
	row := q.db.QueryRow(ctx, getLatestApplicationVersion)
	var i ApplicationVersion
	err := row.Scan(
		&i.VersionID,
		&i.VersionName,
		&i.VersionTimestamp,
		&i.CreatedAt,
	)
	return i, err
}

const listApplicationVersions = `-- name: ListApplicationVersions :many
SELECT version_id, version_name, version_timestamp, created_at
FROM application_versions
ORDER BY version_timestamp DESC
`

func (q *Queries) ListApplicationVersions(ctx context.Context) ([]ApplicationVersion, error) {
	rows, err := q.db.Query(ctx, listApplicationVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationVersion{}
	for rows.Next() {
		var i ApplicationVersion
		if err := rows.Scan(
			&i.VersionID,
			&i.VersionName,
			&i.VersionTimestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationVersionTimestamp = `-- name: UpdateApplicationVersionTimestamp :exec
UPDATE application_versions
SET version_timestamp = $1
WHERE version_name = $2
`

type UpdateApplicationVersionTimestampParams struct {
	VersionTimestamp int64
	VersionName      string
}

func (q *Queries) UpdateApplicationVersionTimestamp(ctx context.Context, arg UpdateApplicationVersionTimestampParams) error {
	_, err := q.db.Exec(ctx, updateApplicationVersionTimestamp, arg.VersionTimestamp, arg.VersionName)
	return err
}
