// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dequeue.sql

package db

import (
	"context"
)

const countPendingWorkflows = `-- name: CountPendingWorkflows :one
SELECT COUNT(*) FROM workflow_status
WHERE name = $1::text AND status = $2::text
`

type CountPendingWorkflowsParams struct {
	Name          string
	PendingStatus string
}

func (q *Queries) CountPendingWorkflows(ctx context.Context, arg CountPendingWorkflowsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingWorkflows, arg.Name, arg.PendingStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRateLimitedWorkflows = `-- name: CountRateLimitedWorkflows :one
SELECT COUNT(*) FROM workflow_status
WHERE name = $1::text
  AND rate_limited = TRUE
  AND status NOT IN ($2::text, $3::text)
  AND started_at_epoch_ms > $4::bigint
`

type CountRateLimitedWorkflowsParams struct {
	Name           string
	EnqueuedStatus string
	DelayedStatus  string
	CutoffMs       int64
}

func (q *Queries) CountRateLimitedWorkflows(ctx context.Context, arg CountRateLimitedWorkflowsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRateLimitedWorkflows,
		arg.Name,
		arg.EnqueuedStatus,
		arg.DelayedStatus,
		arg.CutoffMs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dequeueCandidatesNoWait = `-- name: DequeueCandidatesNoWait :many
SELECT workflow_uuid FROM workflow_status
WHERE name = $1::text AND status = $2::text
  AND (application_version = $3::text OR application_version IS NULL)
ORDER BY priority ASC, created_at ASC
FOR UPDATE NOWAIT
LIMIT $4::int
`

type DequeueCandidatesNoWaitParams struct {
	Name           string
	EnqueuedStatus string
	AppVersion     string
	MaxTasks       int32
}

func (q *Queries) DequeueCandidatesNoWait(ctx context.Context, arg DequeueCandidatesNoWaitParams) ([]string, error) {
	rows, err := q.db.Query(ctx, dequeueCandidatesNoWait,
		arg.Name,
		arg.EnqueuedStatus,
		arg.AppVersion,
		arg.MaxTasks,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var workflow_uuid string
		if err := rows.Scan(&workflow_uuid); err != nil {
			return nil, err
		}
		items = append(items, workflow_uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dequeueCandidatesSkipLocked = `-- name: DequeueCandidatesSkipLocked :many
SELECT workflow_uuid FROM workflow_status
WHERE name = $1::text AND status = $2::text
  AND (application_version = $3::text OR application_version IS NULL)
ORDER BY priority ASC, created_at ASC
FOR UPDATE SKIP LOCKED
LIMIT $4::int
`

type DequeueCandidatesSkipLockedParams struct {
	Name           string
	EnqueuedStatus string
	AppVersion     string
	MaxTasks       int32
}

func (q *Queries) DequeueCandidatesSkipLocked(ctx context.Context, arg DequeueCandidatesSkipLockedParams) ([]string, error) {
	rows, err := q.db.Query(ctx, dequeueCandidatesSkipLocked,
		arg.Name,
		arg.EnqueuedStatus,
		arg.AppVersion,
		arg.MaxTasks,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var workflow_uuid string
		if err := rows.Scan(&workflow_uuid); err != nil {
			return nil, err
		}
		items = append(items, workflow_uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dequeueClaimWorkflow = `-- name: DequeueClaimWorkflow :one
UPDATE workflow_status
SET status = $1::text,
    application_version = $2::text,
    executor_id = $3::text,
    started_at_epoch_ms = $4::bigint,
    rate_limited = $5::boolean,
    workflow_deadline_epoch_ms = CASE
        WHEN workflow_timeout_ms IS NOT NULL AND workflow_deadline_epoch_ms IS NULL
        THEN workflow_timeout_ms + $4::bigint
        ELSE workflow_deadline_epoch_ms
    END
WHERE workflow_uuid = $6 AND status = $7::text
RETURNING name, inputs, serialization
`

type DequeueClaimWorkflowParams struct {
	PendingStatus  string
	AppVersion     string
	ExecutorID     string
	StartedAt      int64
	RateLimited    bool
	WorkflowUuid   string
	EnqueuedStatus string
}

type DequeueClaimWorkflowRow struct {
	Name          *string
	Inputs        *string
	Serialization *string
}

func (q *Queries) DequeueClaimWorkflow(ctx context.Context, arg DequeueClaimWorkflowParams) (DequeueClaimWorkflowRow, error) {
	row := q.db.QueryRow(ctx, dequeueClaimWorkflow,
		arg.PendingStatus,
		arg.AppVersion,
		arg.ExecutorID,
		arg.StartedAt,
		arg.RateLimited,
		arg.WorkflowUuid,
		arg.EnqueuedStatus,
	)
	var i DequeueClaimWorkflowRow
	err := row.Scan(&i.Name, &i.Inputs, &i.Serialization)
	return i, err
}
