// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export.sql

package db

import (
	"context"
)

const exportOperationOutputs = `-- name: ExportOperationOutputs :many
SELECT workflow_uuid, function_id, function_name, output, error, error_encoded,
       started_at_epoch_ms, completed_at_epoch_ms
FROM operation_outputs WHERE workflow_uuid = $1
`

type ExportOperationOutputsRow struct {
	WorkflowUuid       string
	FunctionID         int32
	FunctionName       string
	Output             *string
	Error              *string
	ErrorEncoded       *string
	StartedAtEpochMs   *int64
	CompletedAtEpochMs *int64
}

func (q *Queries) ExportOperationOutputs(ctx context.Context, workflowUuid string) ([]ExportOperationOutputsRow, error) {
	rows, err := q.db.Query(ctx, exportOperationOutputs, workflowUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportOperationOutputsRow{}
	for rows.Next() {
		var i ExportOperationOutputsRow
		if err := rows.Scan(
			&i.WorkflowUuid,
			&i.FunctionID,
			&i.FunctionName,
			&i.Output,
			&i.Error,
			&i.ErrorEncoded,
			&i.StartedAtEpochMs,
			&i.CompletedAtEpochMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportStreams = `-- name: ExportStreams :many
SELECT workflow_uuid, key, value, "offset", function_id FROM streams WHERE workflow_uuid = $1
`

type ExportStreamsRow struct {
	WorkflowUuid string
	Key          string
	Value        string
	Offset       int32
	FunctionID   int32
}

func (q *Queries) ExportStreams(ctx context.Context, workflowUuid string) ([]ExportStreamsRow, error) {
	rows, err := q.db.Query(ctx, exportStreams, workflowUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportStreamsRow{}
	for rows.Next() {
		var i ExportStreamsRow
		if err := rows.Scan(
			&i.WorkflowUuid,
			&i.Key,
			&i.Value,
			&i.Offset,
			&i.FunctionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportWorkflowEvents = `-- name: ExportWorkflowEvents :many
SELECT workflow_uuid, key, value FROM workflow_events WHERE workflow_uuid = $1
`

type ExportWorkflowEventsRow struct {
	WorkflowUuid string
	Key          string
	Value        string
}

func (q *Queries) ExportWorkflowEvents(ctx context.Context, workflowUuid string) ([]ExportWorkflowEventsRow, error) {
	rows, err := q.db.Query(ctx, exportWorkflowEvents, workflowUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportWorkflowEventsRow{}
	for rows.Next() {
		var i ExportWorkflowEventsRow
		if err := rows.Scan(&i.WorkflowUuid, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportWorkflowEventsHistory = `-- name: ExportWorkflowEventsHistory :many
SELECT workflow_uuid, function_id, key, value FROM workflow_events_history WHERE workflow_uuid = $1
`

type ExportWorkflowEventsHistoryRow struct {
	WorkflowUuid string
	FunctionID   int32
	Key          string
	Value        string
}

func (q *Queries) ExportWorkflowEventsHistory(ctx context.Context, workflowUuid string) ([]ExportWorkflowEventsHistoryRow, error) {
	rows, err := q.db.Query(ctx, exportWorkflowEventsHistory, workflowUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportWorkflowEventsHistoryRow{}
	for rows.Next() {
		var i ExportWorkflowEventsHistoryRow
		if err := rows.Scan(
			&i.WorkflowUuid,
			&i.FunctionID,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportWorkflowStatus = `-- name: ExportWorkflowStatus :one
SELECT workflow_uuid, status, name, authenticated_user, assumed_role, authenticated_roles,
       output, error, error_encoded, executor_id, created_at, updated_at, application_version, application_id,
       class_name, config_name, recovery_attempts, queue_name, workflow_timeout_ms,
       workflow_deadline_epoch_ms, started_at_epoch_ms, deduplication_id, inputs, priority,
       queue_partition_key, forked_from, parent_workflow_id, delay_until_epoch_ms, serialization
FROM workflow_status WHERE workflow_uuid = $1
`

type ExportWorkflowStatusRow struct {
	WorkflowUuid            string
	Status                  *string
	Name                    *string
	AuthenticatedUser       *string
	AssumedRole             *string
	AuthenticatedRoles      *string
	Output                  *string
	Error                   *string
	ErrorEncoded            *string
	ExecutorID              *string
	CreatedAt               int64
	UpdatedAt               int64
	ApplicationVersion      *string
	ApplicationID           *string
	ClassName               *string
	ConfigName              *string
	RecoveryAttempts        *int64
	QueueName               *string
	WorkflowTimeoutMs       *int64
	WorkflowDeadlineEpochMs *int64
	StartedAtEpochMs        *int64
	DeduplicationID         *string
	Inputs                  *string
	Priority                int32
	QueuePartitionKey       *string
	ForkedFrom              *string
	ParentWorkflowID        *string
	DelayUntilEpochMs       *int64
	Serialization           *string
}

func (q *Queries) ExportWorkflowStatus(ctx context.Context, workflowUuid string) (ExportWorkflowStatusRow, error) {
	row := q.db.QueryRow(ctx, exportWorkflowStatus, workflowUuid)
	var i ExportWorkflowStatusRow
	err := row.Scan(
		&i.WorkflowUuid,
		&i.Status,
		&i.Name,
		&i.AuthenticatedUser,
		&i.AssumedRole,
		&i.AuthenticatedRoles,
		&i.Output,
		&i.Error,
		&i.ErrorEncoded,
		&i.ExecutorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApplicationVersion,
		&i.ApplicationID,
		&i.ClassName,
		&i.ConfigName,
		&i.RecoveryAttempts,
		&i.QueueName,
		&i.WorkflowTimeoutMs,
		&i.WorkflowDeadlineEpochMs,
		&i.StartedAtEpochMs,
		&i.DeduplicationID,
		&i.Inputs,
		&i.Priority,
		&i.QueuePartitionKey,
		&i.ForkedFrom,
		&i.ParentWorkflowID,
		&i.DelayUntilEpochMs,
		&i.Serialization,
	)
	return i, err
}

const importOperationOutput = `-- name: ImportOperationOutput :exec
INSERT INTO operation_outputs (
    workflow_uuid, function_id, function_name, output, error, error_encoded,
    started_at_epoch_ms, completed_at_epoch_ms
) VALUES ($1, $2::int, $3, $4, $5, $6, $7, $8)
`

type ImportOperationOutputParams struct {
	WorkflowUuid       string
	FunctionID         int32
	FunctionName       string
	Output             *string
	Error              *string
	ErrorEncoded       *string
	StartedAtEpochMs   *int64
	CompletedAtEpochMs *int64
}

func (q *Queries) ImportOperationOutput(ctx context.Context, arg ImportOperationOutputParams) error {
	_, err := q.db.Exec(ctx, importOperationOutput,
		arg.WorkflowUuid,
		arg.FunctionID,
		arg.FunctionName,
		arg.Output,
		arg.Error,
		arg.ErrorEncoded,
		arg.StartedAtEpochMs,
		arg.CompletedAtEpochMs,
	)
	return err
}

const importStream = `-- name: ImportStream :exec
INSERT INTO streams (workflow_uuid, key, value, "offset", function_id)
VALUES ($1, $2, $3::text, $4::int, $5::int)
`

type ImportStreamParams struct {
	WorkflowUuid string
	Key          string
	Value        string
	StreamOffset int32
	FunctionID   int32
}

func (q *Queries) ImportStream(ctx context.Context, arg ImportStreamParams) error {
	_, err := q.db.Exec(ctx, importStream,
		arg.WorkflowUuid,
		arg.Key,
		arg.Value,
		arg.StreamOffset,
		arg.FunctionID,
	)
	return err
}

const importWorkflowEvent = `-- name: ImportWorkflowEvent :exec
INSERT INTO workflow_events (workflow_uuid, key, value)
VALUES ($1, $2, $3::text)
`

type ImportWorkflowEventParams struct {
	WorkflowUuid string
	Key          string
	Value        string
}

func (q *Queries) ImportWorkflowEvent(ctx context.Context, arg ImportWorkflowEventParams) error {
	_, err := q.db.Exec(ctx, importWorkflowEvent, arg.WorkflowUuid, arg.Key, arg.Value)
	return err
}

const importWorkflowEventHistory = `-- name: ImportWorkflowEventHistory :exec
INSERT INTO workflow_events_history (workflow_uuid, function_id, key, value)
VALUES ($1, $2::int, $3, $4::text)
`

type ImportWorkflowEventHistoryParams struct {
	WorkflowUuid string
	FunctionID   int32
	Key          string
	Value        string
}

func (q *Queries) ImportWorkflowEventHistory(ctx context.Context, arg ImportWorkflowEventHistoryParams) error {
	_, err := q.db.Exec(ctx, importWorkflowEventHistory,
		arg.WorkflowUuid,
		arg.FunctionID,
		arg.Key,
		arg.Value,
	)
	return err
}

const importWorkflowStatus = `-- name: ImportWorkflowStatus :exec
INSERT INTO workflow_status (
    workflow_uuid, status, name, authenticated_user, assumed_role, authenticated_roles,
    output, error, error_encoded, executor_id, created_at, updated_at, application_version, application_id,
    class_name, config_name, recovery_attempts, queue_name, workflow_timeout_ms,
    workflow_deadline_epoch_ms, started_at_epoch_ms, deduplication_id, inputs, priority,
    queue_partition_key, forked_from, parent_workflow_id, delay_until_epoch_ms, serialization
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11::bigint, $12::bigint, $13, $14,
    $15, $16, $17, $18, $19,
    $20, $21, $22, $23, $24::int,
    $25, $26, $27, $28, $29
)
`

type ImportWorkflowStatusParams struct {
	WorkflowUuid            string
	Status                  *string
	Name                    *string
	AuthenticatedUser       *string
	AssumedRole             *string
	AuthenticatedRoles      *string
	Output                  *string
	Error                   *string
	ErrorEncoded            *string
	ExecutorID              *string
	CreatedAt               int64
	UpdatedAt               int64
	ApplicationVersion      *string
	ApplicationID           *string
	ClassName               *string
	ConfigName              *string
	RecoveryAttempts        *int64
	QueueName               *string
	WorkflowTimeoutMs       *int64
	WorkflowDeadlineEpochMs *int64
	StartedAtEpochMs        *int64
	DeduplicationID         *string
	Inputs                  *string
	Priority                int32
	QueuePartitionKey       *string
	ForkedFrom              *string
	ParentWorkflowID        *string
	DelayUntilEpochMs       *int64
	Serialization           *string
}

func (q *Queries) ImportWorkflowStatus(ctx context.Context, arg ImportWorkflowStatusParams) error {
	_, err := q.db.Exec(ctx, importWorkflowStatus,
		arg.WorkflowUuid,
		arg.Status,
		arg.Name,
		arg.AuthenticatedUser,
		arg.AssumedRole,
		arg.AuthenticatedRoles,
		arg.Output,
		arg.Error,
		arg.ErrorEncoded,
		arg.ExecutorID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ApplicationVersion,
		arg.ApplicationID,
		arg.ClassName,
		arg.ConfigName,
		arg.RecoveryAttempts,
		arg.QueueName,
		arg.WorkflowTimeoutMs,
		arg.WorkflowDeadlineEpochMs,
		arg.StartedAtEpochMs,
		arg.DeduplicationID,
		arg.Inputs,
		arg.Priority,
		arg.QueuePartitionKey,
		arg.ForkedFrom,
		arg.ParentWorkflowID,
		arg.DelayUntilEpochMs,
		arg.Serialization,
	)
	return err
}
