// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fork.sql

package db

import (
	"context"
)

const forkCopyEventsHistory = `-- name: ForkCopyEventsHistory :exec
INSERT INTO workflow_events_history
    (workflow_uuid, function_id, key, value)
SELECT $1, eh.function_id, eh.key, eh.value
FROM workflow_events_history eh
WHERE eh.workflow_uuid = $2 AND eh.function_id < $3::int
`

type ForkCopyEventsHistoryParams struct {
	ForkedID   string
	OriginalID string
	StartStep  int32
}

func (q *Queries) ForkCopyEventsHistory(ctx context.Context, arg ForkCopyEventsHistoryParams) error {
	_, err := q.db.Exec(ctx, forkCopyEventsHistory, arg.ForkedID, arg.OriginalID, arg.StartStep)
	return err
}

const forkCopyLatestEvents = `-- name: ForkCopyLatestEvents :exec
INSERT INTO workflow_events (workflow_uuid, key, value)
SELECT $1, h.key, h.value
FROM workflow_events_history h
INNER JOIN (
    SELECT eh.key, MAX(eh.function_id) AS max_fid
    FROM workflow_events_history eh
    WHERE eh.workflow_uuid = $2 AND eh.function_id < $3::int
    GROUP BY eh.key
) latest ON h.key = latest.key AND h.function_id = latest.max_fid
WHERE h.workflow_uuid = $2 AND h.function_id < $3::int
`

type ForkCopyLatestEventsParams struct {
	ForkedID   string
	OriginalID string
	StartStep  int32
}

func (q *Queries) ForkCopyLatestEvents(ctx context.Context, arg ForkCopyLatestEventsParams) error {
	_, err := q.db.Exec(ctx, forkCopyLatestEvents, arg.ForkedID, arg.OriginalID, arg.StartStep)
	return err
}

const forkCopyOperationOutputs = `-- name: ForkCopyOperationOutputs :exec
INSERT INTO operation_outputs
    (workflow_uuid, function_id, output, error, function_name, started_at_epoch_ms, completed_at_epoch_ms)
SELECT $1, oo.function_id, oo.output, oo.error, oo.function_name, oo.started_at_epoch_ms, oo.completed_at_epoch_ms
FROM operation_outputs oo
WHERE oo.workflow_uuid = $2 AND oo.function_id < $3::int
`

type ForkCopyOperationOutputsParams struct {
	ForkedID   string
	OriginalID string
	StartStep  int32
}

func (q *Queries) ForkCopyOperationOutputs(ctx context.Context, arg ForkCopyOperationOutputsParams) error {
	_, err := q.db.Exec(ctx, forkCopyOperationOutputs, arg.ForkedID, arg.OriginalID, arg.StartStep)
	return err
}

const forkCopyStreams = `-- name: ForkCopyStreams :exec
INSERT INTO streams
    (workflow_uuid, key, value, "offset", function_id)
SELECT $1, st.key, st.value, st."offset", st.function_id
FROM streams st
WHERE st.workflow_uuid = $2 AND st.function_id < $3::int
`

type ForkCopyStreamsParams struct {
	ForkedID   string
	OriginalID string
	StartStep  int32
}

func (q *Queries) ForkCopyStreams(ctx context.Context, arg ForkCopyStreamsParams) error {
	_, err := q.db.Exec(ctx, forkCopyStreams, arg.ForkedID, arg.OriginalID, arg.StartStep)
	return err
}

const forkInsertWorkflowStatus = `-- name: ForkInsertWorkflowStatus :exec
INSERT INTO workflow_status (
    workflow_uuid, status, name, authenticated_user, assumed_role,
    authenticated_roles, application_version, application_id, queue_name,
    queue_partition_key, inputs, created_at, updated_at, recovery_attempts,
    forked_from, serialization
) VALUES (
    $1, $2::text, $3::text, $4::text, $5::text,
    $6::text, $7::text, $8::text, $9::text,
    $10, $11, $12::bigint, $13::bigint, $14::bigint,
    $15::text, $16::text
)
`

type ForkInsertWorkflowStatusParams struct {
	WorkflowUuid       string
	Status             string
	Name               string
	AuthenticatedUser  string
	AssumedRole        string
	AuthenticatedRoles string
	ApplicationVersion string
	ApplicationID      string
	QueueName          string
	QueuePartitionKey  *string
	Inputs             *string
	CreatedAt          int64
	UpdatedAt          int64
	RecoveryAttempts   int64
	ForkedFrom         string
	Serialization      string
}

func (q *Queries) ForkInsertWorkflowStatus(ctx context.Context, arg ForkInsertWorkflowStatusParams) error {
	_, err := q.db.Exec(ctx, forkInsertWorkflowStatus,
		arg.WorkflowUuid,
		arg.Status,
		arg.Name,
		arg.AuthenticatedUser,
		arg.AssumedRole,
		arg.AuthenticatedRoles,
		arg.ApplicationVersion,
		arg.ApplicationID,
		arg.QueueName,
		arg.QueuePartitionKey,
		arg.Inputs,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.RecoveryAttempts,
		arg.ForkedFrom,
		arg.Serialization,
	)
	return err
}

const markWorkflowForked = `-- name: MarkWorkflowForked :exec
UPDATE workflow_status SET was_forked_from = TRUE WHERE workflow_uuid = $1
`

func (q *Queries) MarkWorkflowForked(ctx context.Context, workflowUuid string) error {
	_, err := q.db.Exec(ctx, markWorkflowForked, workflowUuid)
	return err
}
