// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_workflows.sql

package db

import (
	"context"
)

const listWorkflows = `-- name: ListWorkflows :many
SELECT
    workflow_uuid, status, name, authenticated_user, assumed_role, authenticated_roles,
    executor_id, created_at, updated_at, application_version, application_id,
    recovery_attempts, queue_name, workflow_timeout_ms, workflow_deadline_epoch_ms, started_at_epoch_ms,
    deduplication_id, priority, queue_partition_key, forked_from, parent_workflow_id,
    serialization, delay_until_epoch_ms, was_forked_from, completed_at,
    output, error, inputs
FROM workflow_status
WHERE (NOT $1::boolean OR name = ANY($2::text[]))
  AND (NOT $3::boolean OR queue_name = ANY($4::text[]))
  AND (NOT $5::boolean OR queue_name IS NOT NULL)
  AND (NOT $6::boolean OR workflow_uuid LIKE ANY($7::text[]))
  AND (NOT $8::boolean OR workflow_uuid = ANY($9::text[]))
  AND (NOT $10::boolean OR authenticated_user = ANY($11::text[]))
  AND (NOT $12::boolean OR created_at >= $13::bigint)
  AND (NOT $14::boolean OR created_at <= $15::bigint)
  AND (NOT $16::boolean OR status = ANY($17::text[]))
  AND (NOT $18::boolean OR application_version = ANY($19::text[]))
  AND (NOT $20::boolean OR executor_id = ANY($21::text[]))
  AND (NOT $22::boolean OR forked_from = ANY($23::text[]))
  AND (NOT $24::boolean OR parent_workflow_id = ANY($25::text[]))
  AND (NOT $26::boolean OR deduplication_id = ANY($27::text[]))
  AND (NOT $28::boolean OR completed_at >= $29::bigint)
  AND (NOT $30::boolean OR completed_at <= $31::bigint)
  AND (NOT $32::boolean OR started_at_epoch_ms >= $33::bigint)
  AND (NOT $34::boolean OR started_at_epoch_ms <= $35::bigint)
  AND (NOT $36::boolean OR was_forked_from = $37::boolean)
  AND (NOT $38::boolean OR (
        ($39::boolean AND parent_workflow_id IS NOT NULL) OR
        (NOT $39::boolean AND parent_workflow_id IS NULL)))
ORDER BY
    CASE WHEN $40::boolean THEN created_at END DESC,
    created_at ASC
LIMIT NULLIF($42::bigint, -1)
OFFSET $41::bigint
`

type ListWorkflowsParams struct {
	FilterName            bool
	Names                 []string
	FilterQueue           bool
	QueueNames            []string
	QueuesOnly            bool
	FilterIDPrefix        bool
	IDPrefixes            []string
	FilterIds             bool
	Ids                   []string
	FilterAuthUser        bool
	AuthUsers             []string
	FilterStart           bool
	StartMs               int64
	FilterEnd             bool
	EndMs                 int64
	FilterStatus          bool
	Statuses              []string
	FilterAppVersion      bool
	AppVersions           []string
	FilterExecutor        bool
	ExecutorIds           []string
	FilterForked          bool
	ForkedFroms           []string
	FilterParent          bool
	ParentIds             []string
	FilterDedup           bool
	DedupIds              []string
	FilterCompletedAfter  bool
	CompletedAfter        int64
	FilterCompletedBefore bool
	CompletedBefore       int64
	FilterDequeuedAfter   bool
	DequeuedAfter         int64
	FilterDequeuedBefore  bool
	DequeuedBefore        int64
	FilterWasForked       bool
	WasForked             bool
	FilterHasParent       bool
	HasParent             bool
	SortDesc              bool
	Off                   int64
	Lim                   int64
}

type ListWorkflowsRow struct {
	WorkflowUuid            string
	Status                  *string
	Name                    *string
	AuthenticatedUser       *string
	AssumedRole             *string
	AuthenticatedRoles      *string
	ExecutorID              *string
	CreatedAt               int64
	UpdatedAt               int64
	ApplicationVersion      *string
	ApplicationID           *string
	RecoveryAttempts        *int64
	QueueName               *string
	WorkflowTimeoutMs       *int64
	WorkflowDeadlineEpochMs *int64
	StartedAtEpochMs        *int64
	DeduplicationID         *string
	Priority                int32
	QueuePartitionKey       *string
	ForkedFrom              *string
	ParentWorkflowID        *string
	Serialization           *string
	DelayUntilEpochMs       *int64
	WasForkedFrom           bool
	CompletedAt             *int64
	Output                  *string
	Error                   *string
	Inputs                  *string
}

func (q *Queries) ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]ListWorkflowsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflows,
		arg.FilterName,
		arg.Names,
		arg.FilterQueue,
		arg.QueueNames,
		arg.QueuesOnly,
		arg.FilterIDPrefix,
		arg.IDPrefixes,
		arg.FilterIds,
		arg.Ids,
		arg.FilterAuthUser,
		arg.AuthUsers,
		arg.FilterStart,
		arg.StartMs,
		arg.FilterEnd,
		arg.EndMs,
		arg.FilterStatus,
		arg.Statuses,
		arg.FilterAppVersion,
		arg.AppVersions,
		arg.FilterExecutor,
		arg.ExecutorIds,
		arg.FilterForked,
		arg.ForkedFroms,
		arg.FilterParent,
		arg.ParentIds,
		arg.FilterDedup,
		arg.DedupIds,
		arg.FilterCompletedAfter,
		arg.CompletedAfter,
		arg.FilterCompletedBefore,
		arg.CompletedBefore,
		arg.FilterDequeuedAfter,
		arg.DequeuedAfter,
		arg.FilterDequeuedBefore,
		arg.DequeuedBefore,
		arg.FilterWasForked,
		arg.WasForked,
		arg.FilterHasParent,
		arg.HasParent,
		arg.SortDesc,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowsRow{}
	for rows.Next() {
		var i ListWorkflowsRow
		if err := rows.Scan(
			&i.WorkflowUuid,
			&i.Status,
			&i.Name,
			&i.AuthenticatedUser,
			&i.AssumedRole,
			&i.AuthenticatedRoles,
			&i.ExecutorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicationVersion,
			&i.ApplicationID,
			&i.RecoveryAttempts,
			&i.QueueName,
			&i.WorkflowTimeoutMs,
			&i.WorkflowDeadlineEpochMs,
			&i.StartedAtEpochMs,
			&i.DeduplicationID,
			&i.Priority,
			&i.QueuePartitionKey,
			&i.ForkedFrom,
			&i.ParentWorkflowID,
			&i.Serialization,
			&i.DelayUntilEpochMs,
			&i.WasForkedFrom,
			&i.CompletedAt,
			&i.Output,
			&i.Error,
			&i.Inputs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
