// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"
)

const getMetricStepCount = `-- name: GetMetricStepCount :many
SELECT function_name, COUNT(*) AS count
FROM operation_outputs
WHERE completed_at_epoch_ms >= $1::bigint AND completed_at_epoch_ms < $2::bigint
GROUP BY function_name
`

type GetMetricStepCountParams struct {
	StartMs int64
	EndMs   int64
}

type GetMetricStepCountRow struct {
	FunctionName string
	Count        int64
}

func (q *Queries) GetMetricStepCount(ctx context.Context, arg GetMetricStepCountParams) ([]GetMetricStepCountRow, error) {
	rows, err := q.db.Query(ctx, getMetricStepCount, arg.StartMs, arg.EndMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMetricStepCountRow{}
	for rows.Next() {
		var i GetMetricStepCountRow
		if err := rows.Scan(&i.FunctionName, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricWorkflowCount = `-- name: GetMetricWorkflowCount :many
SELECT name, COUNT(workflow_uuid) AS count
FROM workflow_status
WHERE created_at >= $1::bigint AND created_at < $2::bigint
GROUP BY name
`

type GetMetricWorkflowCountParams struct {
	StartMs int64
	EndMs   int64
}

type GetMetricWorkflowCountRow struct {
	Name  *string
	Count int64
}

func (q *Queries) GetMetricWorkflowCount(ctx context.Context, arg GetMetricWorkflowCountParams) ([]GetMetricWorkflowCountRow, error) {
	rows, err := q.db.Query(ctx, getMetricWorkflowCount, arg.StartMs, arg.EndMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMetricWorkflowCountRow{}
	for rows.Next() {
		var i GetMetricWorkflowCountRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
