// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApplicationVersion struct {
	VersionID        string
	VersionName      string
	VersionTimestamp int64
	CreatedAt        int64
}

type EventDispatchKv struct {
	ServiceName    string
	WorkflowFnName string
	Key            string
	Value          *string
	UpdateSeq      pgtype.Numeric
	UpdateTime     pgtype.Numeric
}

type Notification struct {
	DestinationUuid  string
	Topic            *string
	Message          string
	CreatedAtEpochMs int64
	MessageUuid      string
	Serialization    *string
	Consumed         bool
}

type OperationOutput struct {
	WorkflowUuid       string
	FunctionID         int32
	FunctionName       string
	Output             *string
	Error              *string
	ErrorEncoded       *string
	StartedAtEpochMs   *int64
	CompletedAtEpochMs *int64
	Serialization      *string
}

type Queue struct {
	QueueID           string
	Name              string
	Concurrency       *int32
	WorkerConcurrency *int32
	RateLimitMax      *int32
	PriorityEnabled   bool
	PartitionQueue    bool
	CreatedAt         int64
	UpdatedAt         int64
}

type Stream struct {
	WorkflowUuid  string
	Key           string
	Value         string
	Offset        int32
	FunctionID    int32
	Serialization *string
}

type WorkflowCurrent struct {
	WorkflowName string
	Digest       string
	Since        int64
}

type WorkflowDefinition struct {
	WorkflowName        string
	Digest              string
	InputSchema         *string
	OutputSchema        *string
	DebounceDelayMs     *int64
	DebounceTimeoutMs   *int64
	MaxRecoveryAttempts *int64
	GlobalConcurrency   *int32
	RateLimit           *int32
	RatePeriodMs        *int64
	WorkflowRetentionMs int64
	CronSchedule        *string
	CreatedAt           int64
}

type WorkflowEvent struct {
	WorkflowUuid  string
	Key           string
	Value         string
	Serialization *string
}

type WorkflowEventsHistory struct {
	WorkflowUuid  string
	FunctionID    int32
	Key           string
	Value         string
	Serialization *string
}

type WorkflowOverride struct {
	WorkflowName      string
	GlobalConcurrency *int32
	RateLimit         *int32
	RatePeriodMs      *int64
}

type WorkflowSchedule struct {
	ScheduleID        string
	ScheduleName      string
	WorkflowName      string
	WorkflowClassName *string
	Schedule          string
	Status            string
	Context           string
	LastFiredAt       *string
	AutomaticBackfill bool
	CronTimezone      *string
	QueueName         *string
}

type WorkflowStatus struct {
	WorkflowUuid            string
	Status                  *string
	Name                    *string
	AuthenticatedUser       *string
	AssumedRole             *string
	AuthenticatedRoles      *string
	Request                 *string
	Output                  *string
	Error                   *string
	ErrorEncoded            *string
	ExecutorID              *string
	CreatedAt               int64
	UpdatedAt               int64
	ApplicationVersion      *string
	ApplicationID           *string
	ClassName               *string
	ConfigName              *string
	RecoveryAttempts        *int64
	QueueName               *string
	WorkflowTimeoutMs       *int64
	WorkflowDeadlineEpochMs *int64
	Inputs                  *string
	StartedAtEpochMs        *int64
	DeduplicationID         *string
	Priority                int32
	QueuePartitionKey       *string
	ForkedFrom              *string
	OwnerXid                *string
	ParentWorkflowID        *string
	Serialization           *string
	DelayUntilEpochMs       *int64
	WasForkedFrom           bool
	RateLimited             bool
	CompletedAt             *int64
	DefinitionDigest        *string
}
