// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
)

const consumeOldestMessage = `-- name: ConsumeOldestMessage :one
WITH oldest_entry AS (
    SELECT n.message_uuid FROM notifications n
    WHERE n.destination_uuid = $1 AND n.topic = $2::text AND n.consumed = false
    ORDER BY n.created_at_epoch_ms ASC
    LIMIT 1
)
UPDATE notifications
SET consumed = true
WHERE message_uuid = (SELECT message_uuid FROM oldest_entry)
RETURNING message, serialization
`

type ConsumeOldestMessageParams struct {
	DestinationUuid string
	Topic           string
}

type ConsumeOldestMessageRow struct {
	Message       string
	Serialization *string
}

func (q *Queries) ConsumeOldestMessage(ctx context.Context, arg ConsumeOldestMessageParams) (ConsumeOldestMessageRow, error) {
	row := q.db.QueryRow(ctx, consumeOldestMessage, arg.DestinationUuid, arg.Topic)
	var i ConsumeOldestMessageRow
	err := row.Scan(&i.Message, &i.Serialization)
	return i, err
}

const hasUnconsumedMessage = `-- name: HasUnconsumedMessage :one
SELECT EXISTS (
    SELECT 1 FROM notifications
    WHERE destination_uuid = $1 AND topic = $2::text AND consumed = false
)
`

type HasUnconsumedMessageParams struct {
	DestinationUuid string
	Topic           string
}

func (q *Queries) HasUnconsumedMessage(ctx context.Context, arg HasUnconsumedMessageParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnconsumedMessage, arg.DestinationUuid, arg.Topic)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (destination_uuid, topic, message, serialization, message_uuid, created_at_epoch_ms)
VALUES ($1, $2::text, $3::text, $4::text, $5, $6::bigint)
`

type InsertNotificationParams struct {
	DestinationUuid  string
	Topic            string
	Message          string
	Serialization    string
	MessageUuid      string
	CreatedAtEpochMs int64
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.DestinationUuid,
		arg.Topic,
		arg.Message,
		arg.Serialization,
		arg.MessageUuid,
		arg.CreatedAtEpochMs,
	)
	return err
}
