// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operation_outputs.sql

package db

import (
	"context"
)

const doesPatchExist = `-- name: DoesPatchExist :one
SELECT function_name FROM operation_outputs
WHERE workflow_uuid = $1 AND function_id = $2
`

type DoesPatchExistParams struct {
	WorkflowUuid string
	FunctionID   int32
}

func (q *Queries) DoesPatchExist(ctx context.Context, arg DoesPatchExistParams) (string, error) {
	row := q.db.QueryRow(ctx, doesPatchExist, arg.WorkflowUuid, arg.FunctionID)
	var function_name string
	err := row.Scan(&function_name)
	return function_name, err
}

const getOperationOutput = `-- name: GetOperationOutput :one
SELECT output, error, error_encoded, function_name, serialization
FROM operation_outputs
WHERE workflow_uuid = $1 AND function_id = $2
`

type GetOperationOutputParams struct {
	WorkflowUuid string
	FunctionID   int32
}

type GetOperationOutputRow struct {
	Output        *string
	Error         *string
	ErrorEncoded  *string
	FunctionName  string
	Serialization *string
}

func (q *Queries) GetOperationOutput(ctx context.Context, arg GetOperationOutputParams) (GetOperationOutputRow, error) {
	row := q.db.QueryRow(ctx, getOperationOutput, arg.WorkflowUuid, arg.FunctionID)
	var i GetOperationOutputRow
	err := row.Scan(
		&i.Output,
		&i.Error,
		&i.ErrorEncoded,
		&i.FunctionName,
		&i.Serialization,
	)
	return i, err
}

const getWorkflowSteps = `-- name: GetWorkflowSteps :many
SELECT function_id, function_name, output, error,
       started_at_epoch_ms, completed_at_epoch_ms, serialization
FROM operation_outputs
WHERE workflow_uuid = $1
ORDER BY function_id ASC
`

type GetWorkflowStepsRow struct {
	FunctionID         int32
	FunctionName       string
	Output             *string
	Error              *string
	StartedAtEpochMs   *int64
	CompletedAtEpochMs *int64
	Serialization      *string
}

func (q *Queries) GetWorkflowSteps(ctx context.Context, workflowUuid string) ([]GetWorkflowStepsRow, error) {
	rows, err := q.db.Query(ctx, getWorkflowSteps, workflowUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkflowStepsRow{}
	for rows.Next() {
		var i GetWorkflowStepsRow
		if err := rows.Scan(
			&i.FunctionID,
			&i.FunctionName,
			&i.Output,
			&i.Error,
			&i.StartedAtEpochMs,
			&i.CompletedAtEpochMs,
			&i.Serialization,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPatchMarker = `-- name: InsertPatchMarker :exec
INSERT INTO operation_outputs (workflow_uuid, function_id, function_name)
VALUES ($1, $2, $3)
`

type InsertPatchMarkerParams struct {
	WorkflowUuid string
	FunctionID   int32
	FunctionName string
}

func (q *Queries) InsertPatchMarker(ctx context.Context, arg InsertPatchMarkerParams) error {
	_, err := q.db.Exec(ctx, insertPatchMarker, arg.WorkflowUuid, arg.FunctionID, arg.FunctionName)
	return err
}

const recordOperationResult = `-- name: RecordOperationResult :exec
INSERT INTO operation_outputs (
    workflow_uuid, function_id, output, error, error_encoded, function_name,
    started_at_epoch_ms, completed_at_epoch_ms, serialization
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type RecordOperationResultParams struct {
	WorkflowUuid       string
	FunctionID         int32
	Output             *string
	Error              *string
	ErrorEncoded       *string
	FunctionName       string
	StartedAtEpochMs   *int64
	CompletedAtEpochMs *int64
	Serialization      *string
}

func (q *Queries) RecordOperationResult(ctx context.Context, arg RecordOperationResultParams) error {
	_, err := q.db.Exec(ctx, recordOperationResult,
		arg.WorkflowUuid,
		arg.FunctionID,
		arg.Output,
		arg.Error,
		arg.ErrorEncoded,
		arg.FunctionName,
		arg.StartedAtEpochMs,
		arg.CompletedAtEpochMs,
		arg.Serialization,
	)
	return err
}
