// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streams.sql

package db

import (
	"context"
)

const checkStreamClosed = `-- name: CheckStreamClosed :one
SELECT 1 FROM streams
WHERE workflow_uuid = $1 AND key = $2 AND value = $3
LIMIT 1
`

type CheckStreamClosedParams struct {
	WorkflowUuid string
	Key          string
	Value        string
}

func (q *Queries) CheckStreamClosed(ctx context.Context, arg CheckStreamClosedParams) (int32, error) {
	row := q.db.QueryRow(ctx, checkStreamClosed, arg.WorkflowUuid, arg.Key, arg.Value)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertStreamEntry = `-- name: InsertStreamEntry :exec
INSERT INTO streams (workflow_uuid, key, value, "offset", function_id, serialization)
SELECT $1, $2, $3::text, COALESCE(
    (SELECT MAX("offset") FROM streams WHERE workflow_uuid = $1 AND key = $2), -1
) + 1, $4, $5::text
`

type InsertStreamEntryParams struct {
	WorkflowUuid  string
	Key           string
	Value         string
	FunctionID    int32
	Serialization string
}

func (q *Queries) InsertStreamEntry(ctx context.Context, arg InsertStreamEntryParams) error {
	_, err := q.db.Exec(ctx, insertStreamEntry,
		arg.WorkflowUuid,
		arg.Key,
		arg.Value,
		arg.FunctionID,
		arg.Serialization,
	)
	return err
}

const readStream = `-- name: ReadStream :many
SELECT value, "offset", serialization FROM streams
WHERE workflow_uuid = $1 AND key = $2 AND "offset" >= $3
ORDER BY "offset" ASC
`

type ReadStreamParams struct {
	WorkflowUuid string
	Key          string
	Offset       int32
}

type ReadStreamRow struct {
	Value         string
	Offset        int32
	Serialization *string
}

func (q *Queries) ReadStream(ctx context.Context, arg ReadStreamParams) ([]ReadStreamRow, error) {
	rows, err := q.db.Query(ctx, readStream, arg.WorkflowUuid, arg.Key, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadStreamRow{}
	for rows.Next() {
		var i ReadStreamRow
		if err := rows.Scan(&i.Value, &i.Offset, &i.Serialization); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
