// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_schedules.sql

package db

import (
	"context"
)

const createSchedule = `-- name: CreateSchedule :exec
INSERT INTO workflow_schedules (
    schedule_id, schedule_name, workflow_name, workflow_class_name,
    schedule, context, status, automatic_backfill, cron_timezone, queue_name
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7::text, $8, $9::text, $10
)
`

type CreateScheduleParams struct {
	ScheduleID        string
	ScheduleName      string
	WorkflowName      string
	WorkflowClassName *string
	Schedule          string
	Context           string
	Status            string
	AutomaticBackfill bool
	CronTimezone      string
	QueueName         *string
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) error {
	_, err := q.db.Exec(ctx, createSchedule,
		arg.ScheduleID,
		arg.ScheduleName,
		arg.WorkflowName,
		arg.WorkflowClassName,
		arg.Schedule,
		arg.Context,
		arg.Status,
		arg.AutomaticBackfill,
		arg.CronTimezone,
		arg.QueueName,
	)
	return err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM workflow_schedules WHERE schedule_name = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, scheduleName string) error {
	_, err := q.db.Exec(ctx, deleteSchedule, scheduleName)
	return err
}

const listSchedules = `-- name: ListSchedules :many
SELECT schedule_id, schedule_name, workflow_name, workflow_class_name,
       schedule, status, context, last_fired_at, automatic_backfill,
       cron_timezone, queue_name
FROM workflow_schedules
WHERE (NOT $1::boolean OR status = ANY($2::text[]))
  AND (NOT $3::boolean OR workflow_name = ANY($4::text[]))
  AND (NOT $5::boolean OR schedule_name LIKE ANY($6::text[]))
`

type ListSchedulesParams struct {
	FilterStatuses         bool
	Statuses               []string
	FilterWorkflowNames    bool
	WorkflowNames          []string
	FilterSchedulePrefixes bool
	SchedulePatterns       []string
}

func (q *Queries) ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]WorkflowSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedules,
		arg.FilterStatuses,
		arg.Statuses,
		arg.FilterWorkflowNames,
		arg.WorkflowNames,
		arg.FilterSchedulePrefixes,
		arg.SchedulePatterns,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowSchedule{}
	for rows.Next() {
		var i WorkflowSchedule
		if err := rows.Scan(
			&i.ScheduleID,
			&i.ScheduleName,
			&i.WorkflowName,
			&i.WorkflowClassName,
			&i.Schedule,
			&i.Status,
			&i.Context,
			&i.LastFiredAt,
			&i.AutomaticBackfill,
			&i.CronTimezone,
			&i.QueueName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE workflow_schedules
SET status = $1::text, last_fired_at = $2
WHERE schedule_name = $3
`

type UpdateScheduleParams struct {
	Status       string
	LastFiredAt  *string
	ScheduleName string
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.Exec(ctx, updateSchedule, arg.Status, arg.LastFiredAt, arg.ScheduleName)
	return err
}

const updateScheduleLastFiredAt = `-- name: UpdateScheduleLastFiredAt :exec
UPDATE workflow_schedules
SET last_fired_at = $1::text
WHERE schedule_name = $2
`

type UpdateScheduleLastFiredAtParams struct {
	LastFiredAt  string
	ScheduleName string
}

func (q *Queries) UpdateScheduleLastFiredAt(ctx context.Context, arg UpdateScheduleLastFiredAtParams) error {
	_, err := q.db.Exec(ctx, updateScheduleLastFiredAt, arg.LastFiredAt, arg.ScheduleName)
	return err
}

const workflowExists = `-- name: WorkflowExists :one
SELECT 1 FROM workflow_status WHERE workflow_uuid = $1 LIMIT 1
`

func (q *Queries) WorkflowExists(ctx context.Context, workflowUuid string) (int32, error) {
	row := q.db.QueryRow(ctx, workflowExists, workflowUuid)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
