// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_definitions.sql

package db

import (
	"context"
)

const getWorkflowDefinition = `-- name: GetWorkflowDefinition :one
SELECT global_concurrency, rate_limit, rate_period_ms
FROM workflow_definitions
WHERE workflow_name = $1
`

type GetWorkflowDefinitionRow struct {
	GlobalConcurrency *int32
	RateLimit         *int32
	RatePeriodMs      *int64
}

func (q *Queries) GetWorkflowDefinition(ctx context.Context, workflowName string) (GetWorkflowDefinitionRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowDefinition, workflowName)
	var i GetWorkflowDefinitionRow
	err := row.Scan(&i.GlobalConcurrency, &i.RateLimit, &i.RatePeriodMs)
	return i, err
}

const upsertWorkflowDefinition = `-- name: UpsertWorkflowDefinition :exec
INSERT INTO workflow_definitions (
    workflow_name, global_concurrency, rate_limit, rate_period_ms, workflow_retention_ms
) VALUES ($1, $2, $3, $4, $5::bigint)
ON CONFLICT (workflow_name) DO UPDATE SET
    global_concurrency = EXCLUDED.global_concurrency,
    rate_limit = EXCLUDED.rate_limit,
    rate_period_ms = EXCLUDED.rate_period_ms,
    workflow_retention_ms = EXCLUDED.workflow_retention_ms
`

type UpsertWorkflowDefinitionParams struct {
	WorkflowName        string
	GlobalConcurrency   *int32
	RateLimit           *int32
	RatePeriodMs        *int64
	WorkflowRetentionMs int64
}

func (q *Queries) UpsertWorkflowDefinition(ctx context.Context, arg UpsertWorkflowDefinitionParams) error {
	_, err := q.db.Exec(ctx, upsertWorkflowDefinition,
		arg.WorkflowName,
		arg.GlobalConcurrency,
		arg.RateLimit,
		arg.RatePeriodMs,
		arg.WorkflowRetentionMs,
	)
	return err
}
