// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_status.sql

package db

import (
	"context"
)

const cancelWorkflows = `-- name: CancelWorkflows :many
WITH existing AS (
    SELECT workflow_uuid FROM workflow_status WHERE workflow_uuid = ANY($1::text[])
), updated AS (
    UPDATE workflow_status
    SET status = $2::text, updated_at = $3::bigint, completed_at = $3::bigint,
        started_at_epoch_ms = NULL, queue_name = NULL
    WHERE workflow_uuid = ANY($1::text[])
      AND status NOT IN ($4::text, $5::text, $2::text)
    RETURNING workflow_uuid
)
SELECT workflow_uuid FROM existing
`

type CancelWorkflowsParams struct {
	WorkflowIds     []string
	CancelledStatus string
	NowMs           int64
	SuccessStatus   string
	ErrorStatus     string
}

// Sets matching non-terminal workflows to CANCELLED; returns the subset of
// input IDs that exist (including terminal ones, which are not updated).
func (q *Queries) CancelWorkflows(ctx context.Context, arg CancelWorkflowsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, cancelWorkflows,
		arg.WorkflowIds,
		arg.CancelledStatus,
		arg.NowMs,
		arg.SuccessStatus,
		arg.ErrorStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var workflow_uuid string
		if err := rows.Scan(&workflow_uuid); err != nil {
			return nil, err
		}
		items = append(items, workflow_uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearQueueAssignment = `-- name: ClearQueueAssignment :execrows
UPDATE workflow_status
SET status = $1::text, started_at_epoch_ms = NULL
WHERE workflow_uuid = $2 AND queue_name IS NOT NULL AND status = $3::text
`

type ClearQueueAssignmentParams struct {
	EnqueuedStatus string
	WorkflowUuid   string
	PendingStatus  string
}

func (q *Queries) ClearQueueAssignment(ctx context.Context, arg ClearQueueAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearQueueAssignment, arg.EnqueuedStatus, arg.WorkflowUuid, arg.PendingStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkflows = `-- name: DeleteWorkflows :exec
DELETE FROM workflow_status WHERE workflow_uuid = ANY($1::text[])
`

func (q *Queries) DeleteWorkflows(ctx context.Context, workflowIds []string) error {
	_, err := q.db.Exec(ctx, deleteWorkflows, workflowIds)
	return err
}

const garbageCollectByCutoff = `-- name: GarbageCollectByCutoff :execrows
DELETE FROM workflow_status
WHERE created_at < $1::bigint
  AND status NOT IN ($2::text, $3::text, $4::text)
`

type GarbageCollectByCutoffParams struct {
	Cutoff         int64
	PendingStatus  string
	EnqueuedStatus string
	DelayedStatus  string
}

func (q *Queries) GarbageCollectByCutoff(ctx context.Context, arg GarbageCollectByCutoffParams) (int64, error) {
	result, err := q.db.Exec(ctx, garbageCollectByCutoff,
		arg.Cutoff,
		arg.PendingStatus,
		arg.EnqueuedStatus,
		arg.DelayedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const garbageCollectByRetention = `-- name: GarbageCollectByRetention :execrows
DELETE FROM workflow_status AS ws
WHERE ws.completed_at IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM workflow_definitions AS wd
    WHERE wd.workflow_name = ws.name
      AND ws.completed_at + wd.workflow_retention_ms < $1::bigint
  )
`

func (q *Queries) GarbageCollectByRetention(ctx context.Context, nowMs int64) (int64, error) {
	result, err := q.db.Exec(ctx, garbageCollectByRetention, nowMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeduplicatedWorkflow = `-- name: GetDeduplicatedWorkflow :one
SELECT workflow_uuid
FROM workflow_status
WHERE name = $1 AND deduplication_id = $2
`

type GetDeduplicatedWorkflowParams struct {
	Name            *string
	DeduplicationID *string
}

func (q *Queries) GetDeduplicatedWorkflow(ctx context.Context, arg GetDeduplicatedWorkflowParams) (string, error) {
	row := q.db.QueryRow(ctx, getDeduplicatedWorkflow, arg.Name, arg.DeduplicationID)
	var workflow_uuid string
	err := row.Scan(&workflow_uuid)
	return workflow_uuid, err
}

const getNthNewestCreatedAt = `-- name: GetNthNewestCreatedAt :one
SELECT created_at FROM workflow_status ORDER BY created_at DESC LIMIT 1 OFFSET $1
`

func (q *Queries) GetNthNewestCreatedAt(ctx context.Context, offset int32) (int64, error) {
	row := q.db.QueryRow(ctx, getNthNewestCreatedAt, offset)
	var created_at int64
	err := row.Scan(&created_at)
	return created_at, err
}

const getWorkflowOutcome = `-- name: GetWorkflowOutcome :one
SELECT status, output, error, error_encoded, recovery_attempts, serialization
FROM workflow_status
WHERE workflow_uuid = $1
`

type GetWorkflowOutcomeRow struct {
	Status           *string
	Output           *string
	Error            *string
	ErrorEncoded     *string
	RecoveryAttempts *int64
	Serialization    *string
}

func (q *Queries) GetWorkflowOutcome(ctx context.Context, workflowUuid string) (GetWorkflowOutcomeRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowOutcome, workflowUuid)
	var i GetWorkflowOutcomeRow
	err := row.Scan(
		&i.Status,
		&i.Output,
		&i.Error,
		&i.ErrorEncoded,
		&i.RecoveryAttempts,
		&i.Serialization,
	)
	return i, err
}

const getWorkflowStatusOnly = `-- name: GetWorkflowStatusOnly :one
SELECT status FROM workflow_status WHERE workflow_uuid = $1
`

func (q *Queries) GetWorkflowStatusOnly(ctx context.Context, workflowUuid string) (*string, error) {
	row := q.db.QueryRow(ctx, getWorkflowStatusOnly, workflowUuid)
	var status *string
	err := row.Scan(&status)
	return status, err
}

const insertWorkflowStatus = `-- name: InsertWorkflowStatus :one
INSERT INTO workflow_status (
    workflow_uuid, status, name, queue_name, authenticated_user, assumed_role,
    authenticated_roles, executor_id, application_version, application_id,
    created_at, recovery_attempts, updated_at, workflow_timeout_ms,
    workflow_deadline_epoch_ms, inputs, deduplication_id, priority,
    queue_partition_key, owner_xid, parent_workflow_id, class_name, config_name,
    serialization, delay_until_epoch_ms
) VALUES (
    $1, $2::text, $3::text, $4::text, $5::text, $6::text,
    $7::text, $8::text, $9, $10::text,
    $11::bigint, $12::bigint, $13::bigint, $14,
    $15, $16, $17, $18::int,
    $19, $20, $21, $22, $23,
    $24::text, $25
)
ON CONFLICT (workflow_uuid) DO UPDATE SET
    recovery_attempts = CASE
        WHEN EXCLUDED.status NOT IN ($26::text, $27::text)
        THEN workflow_status.recovery_attempts + $28::bigint
        ELSE workflow_status.recovery_attempts
    END,
    updated_at = EXCLUDED.updated_at,
    executor_id = CASE
        WHEN EXCLUDED.status IN ($26::text, $27::text)
        THEN workflow_status.executor_id
        ELSE EXCLUDED.executor_id
    END
RETURNING recovery_attempts, status, name, queue_name, queue_partition_key,
          workflow_timeout_ms, workflow_deadline_epoch_ms, owner_xid
`

type InsertWorkflowStatusParams struct {
	WorkflowUuid            string
	Status                  string
	Name                    string
	QueueName               string
	AuthenticatedUser       string
	AssumedRole             string
	AuthenticatedRoles      string
	ExecutorID              string
	ApplicationVersion      *string
	ApplicationID           string
	CreatedAt               int64
	RecoveryAttempts        int64
	UpdatedAt               int64
	WorkflowTimeoutMs       *int64
	WorkflowDeadlineEpochMs *int64
	Inputs                  *string
	DeduplicationID         *string
	Priority                int32
	QueuePartitionKey       *string
	OwnerXid                *string
	ParentWorkflowID        *string
	ClassName               *string
	ConfigName              *string
	Serialization           string
	DelayUntilEpochMs       *int64
	EnqueuedStatus          string
	DelayedStatus           string
	RecoveryIncrement       int64
}

type InsertWorkflowStatusRow struct {
	RecoveryAttempts        *int64
	Status                  *string
	Name                    *string
	QueueName               *string
	QueuePartitionKey       *string
	WorkflowTimeoutMs       *int64
	WorkflowDeadlineEpochMs *int64
	OwnerXid                *string
}

func (q *Queries) InsertWorkflowStatus(ctx context.Context, arg InsertWorkflowStatusParams) (InsertWorkflowStatusRow, error) {
	row := q.db.QueryRow(ctx, insertWorkflowStatus,
		arg.WorkflowUuid,
		arg.Status,
		arg.Name,
		arg.QueueName,
		arg.AuthenticatedUser,
		arg.AssumedRole,
		arg.AuthenticatedRoles,
		arg.ExecutorID,
		arg.ApplicationVersion,
		arg.ApplicationID,
		arg.CreatedAt,
		arg.RecoveryAttempts,
		arg.UpdatedAt,
		arg.WorkflowTimeoutMs,
		arg.WorkflowDeadlineEpochMs,
		arg.Inputs,
		arg.DeduplicationID,
		arg.Priority,
		arg.QueuePartitionKey,
		arg.OwnerXid,
		arg.ParentWorkflowID,
		arg.ClassName,
		arg.ConfigName,
		arg.Serialization,
		arg.DelayUntilEpochMs,
		arg.EnqueuedStatus,
		arg.DelayedStatus,
		arg.RecoveryIncrement,
	)
	var i InsertWorkflowStatusRow
	err := row.Scan(
		&i.RecoveryAttempts,
		&i.Status,
		&i.Name,
		&i.QueueName,
		&i.QueuePartitionKey,
		&i.WorkflowTimeoutMs,
		&i.WorkflowDeadlineEpochMs,
		&i.OwnerXid,
	)
	return i, err
}

const markWorkflowMaxRecoveryExceeded = `-- name: MarkWorkflowMaxRecoveryExceeded :exec
UPDATE workflow_status
SET status = $1::text, started_at_epoch_ms = NULL, queue_name = NULL
WHERE workflow_uuid = $2 AND status = $3::text
`

type MarkWorkflowMaxRecoveryExceededParams struct {
	NewStatus     string
	WorkflowUuid  string
	PendingStatus string
}

func (q *Queries) MarkWorkflowMaxRecoveryExceeded(ctx context.Context, arg MarkWorkflowMaxRecoveryExceededParams) error {
	_, err := q.db.Exec(ctx, markWorkflowMaxRecoveryExceeded, arg.NewStatus, arg.WorkflowUuid, arg.PendingStatus)
	return err
}

const resumeWorkflows = `-- name: ResumeWorkflows :many
WITH existing AS (
    SELECT workflow_uuid FROM workflow_status WHERE workflow_uuid = ANY($1::text[])
), updated AS (
    UPDATE workflow_status
    SET status = $2::text, queue_name = $3::text, recovery_attempts = 0,
        workflow_deadline_epoch_ms = NULL, started_at_epoch_ms = NULL,
        updated_at = $4::bigint, completed_at = NULL
    WHERE workflow_uuid = ANY($1::text[])
      AND status NOT IN ($5::text, $6::text)
    RETURNING workflow_uuid
)
SELECT workflow_uuid FROM existing
`

type ResumeWorkflowsParams struct {
	WorkflowIds    []string
	EnqueuedStatus string
	QueueName      string
	NowMs          int64
	SuccessStatus  string
	ErrorStatus    string
}

// Re-enqueues matching non-terminal workflows; returns the subset of input IDs
// that exist (including terminal ones, which are not updated).
func (q *Queries) ResumeWorkflows(ctx context.Context, arg ResumeWorkflowsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, resumeWorkflows,
		arg.WorkflowIds,
		arg.EnqueuedStatus,
		arg.QueueName,
		arg.NowMs,
		arg.SuccessStatus,
		arg.ErrorStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var workflow_uuid string
		if err := rows.Scan(&workflow_uuid); err != nil {
			return nil, err
		}
		items = append(items, workflow_uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkflowDelay = `-- name: SetWorkflowDelay :exec
UPDATE workflow_status
SET delay_until_epoch_ms = $1::bigint, updated_at = $2::bigint
WHERE workflow_uuid = $3 AND status = $4::text
`

type SetWorkflowDelayParams struct {
	DelayUntil   int64
	UpdatedAt    int64
	WorkflowUuid string
	Status       string
}

func (q *Queries) SetWorkflowDelay(ctx context.Context, arg SetWorkflowDelayParams) error {
	_, err := q.db.Exec(ctx, setWorkflowDelay,
		arg.DelayUntil,
		arg.UpdatedAt,
		arg.WorkflowUuid,
		arg.Status,
	)
	return err
}

const transitionDelayedWorkflows = `-- name: TransitionDelayedWorkflows :exec
UPDATE workflow_status
SET status = $1::text
WHERE status = $2::text AND delay_until_epoch_ms <= $3::bigint
`

type TransitionDelayedWorkflowsParams struct {
	NewStatus string
	OldStatus string
	NowMs     int64
}

func (q *Queries) TransitionDelayedWorkflows(ctx context.Context, arg TransitionDelayedWorkflowsParams) error {
	_, err := q.db.Exec(ctx, transitionDelayedWorkflows, arg.NewStatus, arg.OldStatus, arg.NowMs)
	return err
}

const updateWorkflowOutcome = `-- name: UpdateWorkflowOutcome :exec
UPDATE workflow_status
SET status = $1::text, output = $2, error = $3::text, error_encoded = $4,
    updated_at = $5::bigint, completed_at = $5::bigint
WHERE workflow_uuid = $6
  AND NOT (status = $7::text AND $1::text IN ($8::text, $9::text))
`

type UpdateWorkflowOutcomeParams struct {
	Status          string
	Output          *string
	Error           string
	ErrorEncoded    *string
	NowMs           int64
	WorkflowUuid    string
	CancelledStatus string
	SuccessStatus   string
	ErrorStatus     string
}

func (q *Queries) UpdateWorkflowOutcome(ctx context.Context, arg UpdateWorkflowOutcomeParams) error {
	_, err := q.db.Exec(ctx, updateWorkflowOutcome,
		arg.Status,
		arg.Output,
		arg.Error,
		arg.ErrorEncoded,
		arg.NowMs,
		arg.WorkflowUuid,
		arg.CancelledStatus,
		arg.SuccessStatus,
		arg.ErrorStatus,
	)
	return err
}
