// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_status.sql

package db

import (
	"context"
)

const cancelWorkflows = `-- name: CancelWorkflows :many
WITH existing AS (
    SELECT workflow_uuid FROM workflow_status WHERE workflow_uuid = ANY($1::text[])
), updated AS (
    UPDATE workflow_status
    SET status = $2::text, updated_at = $3::bigint, completed_at = $3::bigint,
        started_at_epoch_ms = NULL, queue_name = NULL
    WHERE workflow_uuid = ANY($1::text[])
      AND status NOT IN ($4::text, $5::text, $2::text)
    RETURNING workflow_uuid
)
SELECT workflow_uuid FROM existing
`

type CancelWorkflowsParams struct {
	WorkflowIds     []string
	CancelledStatus string
	NowMs           int64
	SuccessStatus   string
	ErrorStatus     string
}

// Sets matching non-terminal workflows to CANCELLED; returns the subset of
// input IDs that exist (including terminal ones, which are not updated).
func (q *Queries) CancelWorkflows(ctx context.Context, arg CancelWorkflowsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, cancelWorkflows,
		arg.WorkflowIds,
		arg.CancelledStatus,
		arg.NowMs,
		arg.SuccessStatus,
		arg.ErrorStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var workflow_uuid string
		if err := rows.Scan(&workflow_uuid); err != nil {
			return nil, err
		}
		items = append(items, workflow_uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteWorkflows = `-- name: DeleteWorkflows :exec
DELETE FROM workflow_status WHERE workflow_uuid = ANY($1::text[])
`

func (q *Queries) DeleteWorkflows(ctx context.Context, workflowIds []string) error {
	_, err := q.db.Exec(ctx, deleteWorkflows, workflowIds)
	return err
}

const garbageCollectByCutoff = `-- name: GarbageCollectByCutoff :execrows
DELETE FROM workflow_status
WHERE created_at < $1::bigint
  AND status NOT IN ($2::text, $3::text, $4::text)
`

type GarbageCollectByCutoffParams struct {
	Cutoff         int64
	PendingStatus  string
	EnqueuedStatus string
	DelayedStatus  string
}

func (q *Queries) GarbageCollectByCutoff(ctx context.Context, arg GarbageCollectByCutoffParams) (int64, error) {
	result, err := q.db.Exec(ctx, garbageCollectByCutoff,
		arg.Cutoff,
		arg.PendingStatus,
		arg.EnqueuedStatus,
		arg.DelayedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const garbageCollectByRetention = `-- name: GarbageCollectByRetention :execrows
DELETE FROM workflow_status AS ws
WHERE ws.completed_at IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM workflow_definitions AS wd
    WHERE wd.workflow_name = ws.name
      AND ws.completed_at + wd.workflow_retention_ms < $1::bigint
  )
`

func (q *Queries) GarbageCollectByRetention(ctx context.Context, nowMs int64) (int64, error) {
	result, err := q.db.Exec(ctx, garbageCollectByRetention, nowMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeduplicatedWorkflow = `-- name: GetDeduplicatedWorkflow :one
SELECT workflow_uuid
FROM workflow_status
WHERE name = $1 AND deduplication_id = $2
`

type GetDeduplicatedWorkflowParams struct {
	Name            *string
	DeduplicationID *string
}

func (q *Queries) GetDeduplicatedWorkflow(ctx context.Context, arg GetDeduplicatedWorkflowParams) (string, error) {
	row := q.db.QueryRow(ctx, getDeduplicatedWorkflow, arg.Name, arg.DeduplicationID)
	var workflow_uuid string
	err := row.Scan(&workflow_uuid)
	return workflow_uuid, err
}

const getNthNewestCreatedAt = `-- name: GetNthNewestCreatedAt :one
SELECT created_at FROM workflow_status ORDER BY created_at DESC LIMIT 1 OFFSET $1
`

func (q *Queries) GetNthNewestCreatedAt(ctx context.Context, offset int32) (int64, error) {
	row := q.db.QueryRow(ctx, getNthNewestCreatedAt, offset)
	var created_at int64
	err := row.Scan(&created_at)
	return created_at, err
}

const getWorkflowOutcome = `-- name: GetWorkflowOutcome :one
SELECT status, output, error, recovery_attempts, serialization
FROM workflow_status
WHERE workflow_uuid = $1
`

type GetWorkflowOutcomeRow struct {
	Status           *string
	Output           *string
	Error            *string
	RecoveryAttempts *int64
	Serialization    *string
}

func (q *Queries) GetWorkflowOutcome(ctx context.Context, workflowUuid string) (GetWorkflowOutcomeRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowOutcome, workflowUuid)
	var i GetWorkflowOutcomeRow
	err := row.Scan(
		&i.Status,
		&i.Output,
		&i.Error,
		&i.RecoveryAttempts,
		&i.Serialization,
	)
	return i, err
}

const getWorkflowStatusOnly = `-- name: GetWorkflowStatusOnly :one
SELECT status FROM workflow_status WHERE workflow_uuid = $1
`

func (q *Queries) GetWorkflowStatusOnly(ctx context.Context, workflowUuid string) (*string, error) {
	row := q.db.QueryRow(ctx, getWorkflowStatusOnly, workflowUuid)
	var status *string
	err := row.Scan(&status)
	return status, err
}

const resumeWorkflows = `-- name: ResumeWorkflows :many
WITH existing AS (
    SELECT workflow_uuid FROM workflow_status WHERE workflow_uuid = ANY($1::text[])
), updated AS (
    UPDATE workflow_status
    SET status = $2::text, queue_name = $3::text, recovery_attempts = 0,
        workflow_deadline_epoch_ms = NULL, started_at_epoch_ms = NULL,
        updated_at = $4::bigint, completed_at = NULL
    WHERE workflow_uuid = ANY($1::text[])
      AND status NOT IN ($5::text, $6::text)
    RETURNING workflow_uuid
)
SELECT workflow_uuid FROM existing
`

type ResumeWorkflowsParams struct {
	WorkflowIds    []string
	EnqueuedStatus string
	QueueName      string
	NowMs          int64
	SuccessStatus  string
	ErrorStatus    string
}

// Re-enqueues matching non-terminal workflows; returns the subset of input IDs
// that exist (including terminal ones, which are not updated).
func (q *Queries) ResumeWorkflows(ctx context.Context, arg ResumeWorkflowsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, resumeWorkflows,
		arg.WorkflowIds,
		arg.EnqueuedStatus,
		arg.QueueName,
		arg.NowMs,
		arg.SuccessStatus,
		arg.ErrorStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var workflow_uuid string
		if err := rows.Scan(&workflow_uuid); err != nil {
			return nil, err
		}
		items = append(items, workflow_uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkflowDelay = `-- name: SetWorkflowDelay :exec
UPDATE workflow_status
SET delay_until_epoch_ms = $1::bigint, updated_at = $2::bigint
WHERE workflow_uuid = $3 AND status = $4::text
`

type SetWorkflowDelayParams struct {
	DelayUntil   int64
	UpdatedAt    int64
	WorkflowUuid string
	Status       string
}

func (q *Queries) SetWorkflowDelay(ctx context.Context, arg SetWorkflowDelayParams) error {
	_, err := q.db.Exec(ctx, setWorkflowDelay,
		arg.DelayUntil,
		arg.UpdatedAt,
		arg.WorkflowUuid,
		arg.Status,
	)
	return err
}

const transitionDelayedWorkflows = `-- name: TransitionDelayedWorkflows :exec
UPDATE workflow_status
SET status = $1::text
WHERE status = $2::text AND delay_until_epoch_ms <= $3::bigint
`

type TransitionDelayedWorkflowsParams struct {
	NewStatus string
	OldStatus string
	NowMs     int64
}

func (q *Queries) TransitionDelayedWorkflows(ctx context.Context, arg TransitionDelayedWorkflowsParams) error {
	_, err := q.db.Exec(ctx, transitionDelayedWorkflows, arg.NewStatus, arg.OldStatus, arg.NowMs)
	return err
}

const updateWorkflowOutcome = `-- name: UpdateWorkflowOutcome :exec
UPDATE workflow_status
SET status = $1::text, output = $2, error = $3::text,
    updated_at = $4::bigint, completed_at = $4::bigint
WHERE workflow_uuid = $5
  AND NOT (status = $6::text AND $1::text IN ($7::text, $8::text))
`

type UpdateWorkflowOutcomeParams struct {
	Status          string
	Output          *string
	Error           string
	NowMs           int64
	WorkflowUuid    string
	CancelledStatus string
	SuccessStatus   string
	ErrorStatus     string
}

func (q *Queries) UpdateWorkflowOutcome(ctx context.Context, arg UpdateWorkflowOutcomeParams) error {
	_, err := q.db.Exec(ctx, updateWorkflowOutcome,
		arg.Status,
		arg.Output,
		arg.Error,
		arg.NowMs,
		arg.WorkflowUuid,
		arg.CancelledStatus,
		arg.SuccessStatus,
		arg.ErrorStatus,
	)
	return err
}
