// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_events.sql

package db

import (
	"context"
)

const getWorkflowEvent = `-- name: GetWorkflowEvent :one
SELECT value, serialization FROM workflow_events
WHERE workflow_uuid = $1 AND key = $2
`

type GetWorkflowEventParams struct {
	WorkflowUuid string
	Key          string
}

type GetWorkflowEventRow struct {
	Value         string
	Serialization *string
}

func (q *Queries) GetWorkflowEvent(ctx context.Context, arg GetWorkflowEventParams) (GetWorkflowEventRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowEvent, arg.WorkflowUuid, arg.Key)
	var i GetWorkflowEventRow
	err := row.Scan(&i.Value, &i.Serialization)
	return i, err
}

const insertWorkflowEventHistory = `-- name: InsertWorkflowEventHistory :exec
INSERT INTO workflow_events_history (workflow_uuid, function_id, key, value, serialization)
VALUES ($1, $2, $3, $4::text, $5::text)
ON CONFLICT (workflow_uuid, function_id, key)
DO UPDATE SET value = EXCLUDED.value, serialization = EXCLUDED.serialization
`

type InsertWorkflowEventHistoryParams struct {
	WorkflowUuid  string
	FunctionID    int32
	Key           string
	Value         string
	Serialization string
}

func (q *Queries) InsertWorkflowEventHistory(ctx context.Context, arg InsertWorkflowEventHistoryParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowEventHistory,
		arg.WorkflowUuid,
		arg.FunctionID,
		arg.Key,
		arg.Value,
		arg.Serialization,
	)
	return err
}

const upsertWorkflowEvent = `-- name: UpsertWorkflowEvent :exec
INSERT INTO workflow_events (workflow_uuid, key, value, serialization)
VALUES ($1, $2, $3::text, $4::text)
ON CONFLICT (workflow_uuid, key)
DO UPDATE SET value = EXCLUDED.value, serialization = EXCLUDED.serialization
`

type UpsertWorkflowEventParams struct {
	WorkflowUuid  string
	Key           string
	Value         string
	Serialization string
}

func (q *Queries) UpsertWorkflowEvent(ctx context.Context, arg UpsertWorkflowEventParams) error {
	_, err := q.db.Exec(ctx, upsertWorkflowEvent,
		arg.WorkflowUuid,
		arg.Key,
		arg.Value,
		arg.Serialization,
	)
	return err
}
